### ISSUE TITLE
Generate a Multi Filter Function

### ISSUE THREAD

**Issue by Djis247** [Djis247/p2#1]
## Problem 1: Generate a Multi Filter Function

In your `p2` directory, make a new file named `make-multi-filter.js`. The code for your Multi Filter Function will go in this file.

Declare a global function named `MakeMultiFilter` that takes an array (`originalArray`) as a parameter and returns a function that can be used to filter the elements of this array. The returned function (`arrayFilterer`) internally keeps track of a notion called `currentArray`. Initially, `currentArray` is set to be identical to `originalArray`. The `arrayFilterer` function takes two functions as parameters. They are:

1. `filterCriteria` - A function that takes an array element as a parameter and returns a boolean. This function is called on every element of `currentArray` and `currentArray` is updated to reflect the results of the `filterCriteria` function. If the `filterCriteria` function returns `false` for an element, that element should be removed from `currentArray`. Otherwise, it is left in `currentArray`. If `filterCriteria` is not a function, the returned function (`arrayFilterer`) should immediately return the value of `currentArray` with no filtering performed.

2. `callback` - A function that will be called when the filtering is done. `callback` takes the value of `currentArray` as an argument. Accessing `this` inside the callback function should reference the value of originalArray. If callback is not a function, it should be ignored. callback does not have a return value.

The `arrayFilterer` function should return itself unless the `filterCriteria` parameter is not specified in which case it should return the `currentArray`. It must be possible to have multiple `arrayFilterer` functions operating at the same time.

The following code shows how one might make use of the functions you define in this problem:

```javascript
// Invoking MakeMultiFilter() with originalArray = [1, 2, 3] returns a
// function, saved in the variable arrayFilterer1, that can be used to
// repeatedly filter the input array
var arrayFilterer1 = MakeMultiFilter([1, 2, 3]);

// Call arrayFilterer1 (with a callback function) to filter out all the numbers
// not equal to 2.
arrayFilterer1(function (elem) {
  return elem !== 2; // check if element is not equal to 2
}, function (currentArray) {
  // 'this' within the callback function should refer to originalArray which is [1, 2, 3]
  console.log(this); // prints [1, 2, 3]
  console.log(currentArray); // prints [1, 3]
});

// Call arrayFilterer1 (without a callback function) to filter out all the
// elements not equal to 3.
arrayFilterer1(function (elem) {
  return elem !== 3; // check if element is not equal to 3
});

// Calling arrayFilterer1 with no filterCriteria should return the currentArray.
var currentArray = arrayFilterer1();
console.log('currentArray', currentArray); // prints [1] since we filtered out 2 and 3

// Since arrayFilterer returns itself, calls can be chained
function filterTwos(elem) { return elem !== 2; }
function filterThrees(elem) { return elem !== 3; }
var arrayFilterer2 = MakeMultiFilter([1, 2, 3]);
var currentArray2 = arrayFilterer2(filterTwos)(filterThrees)();
console.log('currentArray2', currentArray2); // prints [1] since we filtered out 2 and 3

// Multiple active filters at the same time
var arrayFilterer3 = MakeMultiFilter([1, 2, 3]);
var arrayFilterer4 = MakeMultiFilter([4, 5, 6]);
console.log(arrayFilterer3(filterTwos)()); // prints [1, 3]
console.log(arrayFilterer4(filterThrees)()); // prints [4, 5, 6]
```

**Comment by dsprad99** [comment]
Completed make-multi-filter file
